### PR TITLE
background blur

### PR DESCRIPTION
**Pull request by otanim**

### CODE REVIEW

**Comment by fxfactorial** [comment]
Thanks, but can you make this one commit and do it in the site.jsx, then generate that and have in the commit `site.jsx`, `index.html` committed? 

Hint, reset HEAD~4, then a force push

**Comment by otanim** [comment]
@fxfactorial oh, then why do we even need that **index.html** ?
We can exclude it from repository, by way of add a new line in **.gitignore**

**Comment by fxfactorial** [comment]
@otanim because github pages needs the `index.html` to render from :)

**Comment by fxfactorial** [comment]
Nice! Thanks!

**Pull request merged**
